feat: add slack notification

diff --git a/.github/workflows/update-sigmarule.yaml b/.github/workflows/update-sigmarule.yaml
--- a/.github/workflows/update-sigmarule.yaml
+++ b/.github/workflows/update-sigmarule.yaml
@@ -96,10 +96,27 @@ jobs:
           ./hayabusa-${LATEST_VER#v}-lin-x64-gnu csv-timeline -d ../../hayabusa-sample-evtx -r ../../hayabusa-rules -w -o out.csv -D -n -u  -C | grep "Rule parsing error" | wc -l | grep 0
           if [ $? -eq 0 ]; then
               echo "No rule parse error."
+              echo "RULE_PARSE_ERROR=0" >> $GITHUB_ENV
           else
               cat ./logs/*
-              false
+              echo "RULE_PARSE_ERROR=1" >> $GITHUB_ENV
           fi
+          exit 0
+
+      - name: Notify Slack
+        if: env.RULE_PARSE_ERROR == '1'
+        uses: 8398a7/action-slack@v3
+        with:
+          status: failure
+          fields: job
+        env:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+
+      - name: check rule parse error status
+        if: env.RULE_PARSE_ERROR == '1'
+        run: |
+          echo "Rule parse error found. Please check the logs above."
+          exit 1
 
   updateSigmaRule:
     needs: rule-parse-error-check
